In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


# Import iterative Imputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
# To preprocess the data
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder, OrdinalEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer, KNNImputer

# Import iterative Imputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# For Machine Learning
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score

# Metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_absolute_error, precision_score, mean_squared_error, r2_score

# For Classification\Regression Tasks
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingRegressor, GradientBoostingClassifier
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split, GridSearchCV, LeaveOneOut, RandomizedSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split


from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
# For Machine Learning
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score

# Metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_absolute_error, precision_score, mean_squared_error, r2_score

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [39]:
df = pd.read_csv("H:\\MY\\Computer Science\\Python Codes\\ML Pipeline\\Final Data of Salary Dataset.csv")
df

,Unnamed: 0,Age,Gender,Education Level,Years of Experience,Salary,Quantile_X,Quantile_Y,Quantile_Z
0,0,32.0,Male,Bachelor's,5.0,103000.0,0.061513,-0.257495,-0.121416
1,1,28.0,Female,Master's,3.0,65000.0,-0.604448,-0.700711,-0.723343
2,2,45.0,NaN,PhD,15.4,150000.0,1.394512,1.207012,0.551076
3,3,36.0,NaN,Bachelor's,7.0,60000.0,0.556927,0.056486,-0.837338
4,4,52.0,Male,Master's,8.0,200000.0,5.199338,0.208505,1.994971
...,...,...,...,...,...,...,...,...,...
6545,6698,49.0,Female,PhD,20.0,200000.0,1.942703,1.895259,1.994971
6546,6699,32.0,Male,High School,3.0,50000.0,0.061513,-0.700711,-1.181921
6547,6700,30.0,Female,Bachelor's,4.0,55000.0,-0.232930,-0.445919,-0.999986
6548,6701,46.0,Male,Master's,14.0,140000.0,1.533612,1.025123,0.407442
6549,6702,26.0,Female,High School,1.0,35000.0,-1.123415,-1.558482,-1.588771

In [40]:
df.drop(columns=["Unnamed: 0", "Quantile_X",	"Quantile_Y",	"Quantile_Z"], inplace=True)
df

       Age  Gender Education Level  Years of Experience    Salary
0     32.0    Male      Bachelor's                  5.0  103000.0
1     28.0  Female        Master's                  3.0   65000.0
2     45.0     NaN             PhD                 15.4  150000.0
3     36.0     NaN      Bachelor's                  7.0   60000.0
4     52.0    Male        Master's                  8.0  200000.0
...    ...     ...             ...                  ...       ...
6545  49.0  Female             PhD                 20.0  200000.0
6546  32.0    Male     High School                  3.0   50000.0
6547  30.0  Female      Bachelor's                  4.0   55000.0
6548  46.0    Male        Master's                 14.0  140000.0
6549  26.0  Female     High School                  1.0   35000.0

[6550 rows x 5 columns]

In [41]:
df.isnull().sum()

Age                    0
Gender                 3
Education Level        3
Years of Experience    0
Salary                 0
dtype: int64

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6550 entries, 0 to 6549
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6550 non-null   float64
 1   Gender               6547 non-null   object
 2   Education Level      6547 non-null   object
 3   Years of Experience  6550 non-null   float64
 4   Salary               6550 non-null   float64
dtypes: float64(3), object(2)
memory usage: 256.0+ KB

In [43]:
le = LabelEncoder()
df["Gender"] = le.fit_transform(df["Gender"])

In [44]:
le = LabelEncoder()
df["Education Level"] = le.fit_transform(df["Education Level"])

In [45]:
from sklearn.impute import KNNImputer
impute = KNNImputer()
df["Gender"] = impute.fit_transform(df[["Gender"]])

In [46]:
from sklearn.impute import KNNImputer
impute = KNNImputer()
df["Education Level"] = impute.fit_transform(df[["Education Level"]])

In [47]:
df

       Age  Gender  Education Level  Years of Experience    Salary
0     32.0     1.0              0.0                  5.0  103000.0
1     28.0     0.0              2.0                  3.0   65000.0
2     45.0     3.0              3.0                 15.4  150000.0
3     36.0     3.0              0.0                  7.0   60000.0
4     52.0     1.0              2.0                  8.0  200000.0
...    ...     ...              ...                  ...       ...
6545  49.0     0.0              3.0                 20.0  200000.0
6546  32.0     1.0              1.0                  3.0   50000.0
6547  30.0     0.0              0.0                  4.0   55000.0
6548  46.0     1.0              2.0                 14.0  140000.0
6549  26.0     0.0              1.0                  1.0   35000.0

[6550 rows x 5 columns]

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6550 entries, 0 to 6549
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6550 non-null   float64
 1   Gender               6550 non-null   float64
 2   Education Level      6550 non-null   float64
 3   Years of Experience  6550 non-null   float64
 4   Salary               6550 non-null   float64
dtypes: float64(5)
memory usage: 256.0 KB

In [49]:
df.shape

(6550, 5)

In [50]:
print(df["Salary"].min())
print(df["Salary"].max())

350.0
250000.0

In [51]:
X = df.drop("Salary", axis=1)
y = df["Salary"]

X_train, X_test, y_train, y_test =train_test_split(X,y, test_size=0.2, random_state=42)

import numpy as np

# Convert to numeric if possible
X_train = np.array(X_train, dtype=np.float32)
X_test  = np.array(X_test, dtype=np.float32)
y_train = np.array(y_train, dtype=np.float32)
y_test  = np.array(y_test, dtype=np.float32)

In [52]:
model = models.Sequential([
    
    layers.Dense(512, activation='relu', input_shape=(4,)),
    layers.Dense(256, activation='relu'),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(16, activation='relu'),
    layers.Dense(1, activation='linear'),
])

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_16 (Dense)            (None, 512)               2560

 dense_17 (Dense)            (None, 256)               131328

 dense_18 (Dense)            (None, 128)               32896

 dense_19 (Dense)            (None, 64)                8256

 dense_20 (Dense)            (None, 32)                2080

 dense_21 (Dense)            (None, 16)                528

 dense_22 (Dense)            (None, 1)                 17

=================================================================
Total params: 177,665
Trainable params: 177,665
Non-trainable params: 0
_________________________________________________________________

In [53]:
model.compile(optimizer='adam',
              loss='mse',
              metrics=['mae'])

In [63]:
history= model.fit(X_train, y_train, epochs= 180,
                 validation_data=(X_test, y_test))

Epoch 1/180
164/164 [==============================] - 2s 14ms/step - loss: 361675360.0000 - mae: 14104.6533 - val_loss: 439481760.0000 - val_mae: 14973.3516
Epoch 2/180
164/164 [==============================] - 2s 12ms/step - loss: 363820672.0000 - mae: 14055.1250 - val_loss: 490306336.0000 - val_mae: 16752.8926
Epoch 3/180
164/164 [==============================] - 2s 11ms/step - loss: 376869664.0000 - mae: 14401.8057 - val_loss: 426833312.0000 - val_mae: 15513.3926
Epoch 4/180
164/164 [==============================] - 2s 11ms/step - loss: 377825696.0000 - mae: 14527.3818 - val_loss: 412185408.0000 - val_mae: 14692.7500
Epoch 5/180
164/164 [==============================] - 2s 9ms/step - loss: 362351008.0000 - mae: 14122.6104 - val_loss: 411654208.0000 - val_mae: 14969.0732
Epoch 6/180
164/164 [==============================] - 2s 11ms/step - loss: 366948960.0000 - mae: 14250.8379 - val_loss: 425176800.0000 - val_mae: 15066.6338
Epoch 7/180
164/164 [==============================] - 2s 11ms/step - loss: 358754176.0000 - mae: 13978.2275 - val_loss: 414944928.0000 - val_mae: 14950.2920
Epoch 8/180
164/164 [==============================] - 2s 11ms/step - loss: 367094496.0000 - mae: 14304.5195 - val_loss: 421239936.0000 - val_mae: 15075.5791
Epoch 9/180
164/164 [==============================] - 2s 10ms/step - loss: 372823008.0000 - mae: 14379.7051 - val_loss: 429244448.0000 - val_mae: 15373.4248
Epoch 10/180
164/164 [==============================] - 2s 11ms/step - loss: 378695232.0000 - mae: 14429.2920 - val_loss: 447646944.0000 - val_mae: 16306.8564
Epoch 11/180
164/164 [==============================] - 2s 10ms/step - loss: 359831776.0000 - mae: 14035.3115 - val_loss: 413989696.0000 - val_mae: 14816.3203
Epoch 12/180
164/164 [==============================] - 2s 11ms/step - loss: 360761184.0000 - mae: 14077.1250 - val_loss: 418531136.0000 - val_mae: 14972.0273
Epoch 13/180
164/164 [==============================] - 2s 13ms/step - loss: 364016576.0000 - mae: 14126.1553 - val_loss: 439034432.0000 - val_mae: 15724.9736
Epoch 14/180
164/164 [==============================] - 2s 11ms/step - loss: 360450944.0000 - mae: 14090.6582 - val_loss: 397989408.0000 - val_mae: 14877.2061
Epoch 15/180
164/164 [==============================] - 2s 11ms/step - loss: 359692800.0000 - mae: 14026.4746 - val_loss: 411457728.0000 - val_mae: 15176.6094
Epoch 16/180
164/164 [==============================] - 2s 15ms/step - loss: 364448096.0000 - mae: 14048.6836 - val_loss: 406728832.0000 - val_mae: 14914.1240
Epoch 17/180
164/164 [==============================] - 2s 13ms/step - loss: 371695840.0000 - mae: 14329.8623 - val_loss: 423882080.0000 - val_mae: 15100.4658
Epoch 18/180
164/164 [==============================] - 2s 13ms/step - loss: 357279872.0000 - mae: 14017.0195 - val_loss: 418338592.0000 - val_mae: 15016.1621
Epoch 19/180
164/164 [==============================] - 2s 14ms/step - loss: 356738272.0000 - mae: 13895.8789 - val_loss: 438885984.0000 - val_mae: 15017.3477
Epoch 20/180
164/164 [==============================] - 2s 13ms/step - loss: 360406016.0000 - mae: 14093.1113 - val_loss: 409868224.0000 - val_mae: 15082.7051
Epoch 21/180
164/164 [==============================] - 2s 12ms/step - loss: 358591968.0000 - mae: 14026.8457 - val_loss: 478209536.0000 - val_mae: 16588.0625
Epoch 22/180
164/164 [==============================] - 2s 13ms/step - loss: 363903648.0000 - mae: 14108.7773 - val_loss: 418408096.0000 - val_mae: 15084.0469
Epoch 23/180
164/164 [==============================] - 2s 12ms/step - loss: 360457856.0000 - mae: 14028.5088 - val_loss: 434389824.0000 - val_mae: 15794.7461
Epoch 24/180
164/164 [==============================] - 2s 12ms/step - loss: 366529184.0000 - mae: 14160.1240 - val_loss: 423426336.0000 - val_mae: 14967.9482
Epoch 25/180
164/164 [==============================] - 2s 12ms/step - loss: 360563392.0000 - mae: 14056.8691 - val_loss: 439415968.0000 - val_mae: 15794.0898
Epoch 26/180
164/164 [==============================] - 2s 12ms/step - loss: 379868128.0000 - mae: 14507.3770 - val_loss: 428230496.0000 - val_mae: 15071.6064
Epoch 27/180
164/164 [==============================] - 2s 12ms/step - loss: 367285120.0000 - mae: 14255.8721 - val_loss: 429661120.0000 - val_mae: 15316.4902
Epoch 28/180
164/164 [==============================] - 2s 14ms/step - loss: 361248256.0000 - mae: 14022.2705 - val_loss: 420084320.0000 - val_mae: 14785.3545
Epoch 29/180
164/164 [==============================] - 2s 13ms/step - loss: 359080640.0000 - mae: 14017.2197 - val_loss: 429382976.0000 - val_mae: 14845.0332
Epoch 30/180
164/164 [==============================] - 2s 11ms/step - loss: 363889472.0000 - mae: 14219.7646 - val_loss: 463834240.0000 - val_mae: 16074.0596
Epoch 31/180
164/164 [==============================] - 2s 13ms/step - loss: 362503648.0000 - mae: 14070.0615 - val_loss: 420654720.0000 - val_mae: 15019.7705
Epoch 32/180
164/164 [==============================] - 2s 11ms/step - loss: 360652672.0000 - mae: 14040.9141 - val_loss: 415847872.0000 - val_mae: 14845.0791
Epoch 33/180
164/164 [==============================] - 2s 13ms/step - loss: 367516928.0000 - mae: 14272.0518 - val_loss: 429804160.0000 - val_mae: 15346.8232
Epoch 34/180
164/164 [==============================] - 2s 11ms/step - loss: 369323616.0000 - mae: 14268.8027 - val_loss: 545229056.0000 - val_mae: 17967.4277
Epoch 35/180
164/164 [==============================] - 2s 11ms/step - loss: 370727104.0000 - mae: 14309.9355 - val_loss: 426364000.0000 - val_mae: 15046.6670
Epoch 36/180
164/164 [==============================] - 2s 11ms/step - loss: 357420704.0000 - mae: 14014.1738 - val_loss: 400569216.0000 - val_mae: 14843.5156
Epoch 37/180
164/164 [==============================] - 2s 12ms/step - loss: 359889632.0000 - mae: 14009.7539 - val_loss: 412827008.0000 - val_mae: 15119.2061
Epoch 38/180
164/164 [==============================] - 2s 12ms/step - loss: 360787872.0000 - mae: 14019.2246 - val_loss: 427800544.0000 - val_mae: 16090.1680
Epoch 39/180
164/164 [==============================] - 2s 11ms/step - loss: 361873568.0000 - mae: 14049.6211 - val_loss: 413151072.0000 - val_mae: 14940.0898
Epoch 40/180
164/164 [==============================] - 2s 10ms/step - loss: 358349152.0000 - mae: 13990.3906 - val_loss: 423551200.0000 - val_mae: 15170.7637
Epoch 41/180
164/164 [==============================] - 2s 11ms/step - loss: 365749344.0000 - mae: 14218.5850 - val_loss: 510324384.0000 - val_mae: 17137.8047
Epoch 42/180
164/164 [==============================] - 2s 10ms/step - loss: 364842976.0000 - mae: 14180.8184 - val_loss: 412083008.0000 - val_mae: 14952.7744
Epoch 43/180
164/164 [==============================] - 2s 12ms/step - loss: 356878880.0000 - mae: 13935.4014 - val_loss: 412366560.0000 - val_mae: 14703.5957
Epoch 44/180
164/164 [==============================] - 2s 12ms/step - loss: 369231232.0000 - mae: 14256.6348 - val_loss: 416638080.0000 - val_mae: 14927.9873
Epoch 45/180
164/164 [==============================] - 2s 11ms/step - loss: 359175808.0000 - mae: 13990.4668 - val_loss: 408285248.0000 - val_mae: 14805.0488
Epoch 46/180
164/164 [==============================] - 2s 10ms/step - loss: 357361536.0000 - mae: 14023.1484 - val_loss: 457231968.0000 - val_mae: 15445.5469
Epoch 47/180
164/164 [==============================] - 2s 11ms/step - loss: 354267008.0000 - mae: 13900.6289 - val_loss: 411092960.0000 - val_mae: 14743.6777
Epoch 48/180
164/164 [==============================] - 2s 11ms/step - loss: 377021984.0000 - mae: 14404.8564 - val_loss: 413114432.0000 - val_mae: 14757.3447
Epoch 49/180
164/164 [==============================] - 2s 12ms/step - loss: 351057280.0000 - mae: 13843.2686 - val_loss: 431576576.0000 - val_mae: 15478.1865
Epoch 50/180
164/164 [==============================] - 2s 11ms/step - loss: 357875200.0000 - mae: 13998.1572 - val_loss: 468828448.0000 - val_mae: 16184.2686
Epoch 51/180
164/164 [==============================] - 2s 11ms/step - loss: 360981824.0000 - mae: 14011.9209 - val_loss: 423655584.0000 - val_mae: 14857.9385
Epoch 52/180
164/164 [==============================] - 2s 11ms/step - loss: 355825664.0000 - mae: 13875.2383 - val_loss: 398875648.0000 - val_mae: 14604.1387
Epoch 53/180
164/164 [==============================] - 2s 12ms/step - loss: 358740224.0000 - mae: 13948.4463 - val_loss: 441613920.0000 - val_mae: 15444.3223
Epoch 54/180
164/164 [==============================] - 2s 11ms/step - loss: 356629120.0000 - mae: 13952.6777 - val_loss: 410754144.0000 - val_mae: 14873.2568
Epoch 55/180
164/164 [==============================] - 2s 10ms/step - loss: 372461536.0000 - mae: 14304.1787 - val_loss: 468866464.0000 - val_mae: 16539.2305
Epoch 56/180
164/164 [==============================] - 2s 11ms/step - loss: 361174656.0000 - mae: 14094.2598 - val_loss: 477764288.0000 - val_mae: 16803.4883
Epoch 57/180
164/164 [==============================] - 2s 10ms/step - loss: 359676160.0000 - mae: 14065.5605 - val_loss: 443713696.0000 - val_mae: 15991.0381
Epoch 58/180
164/164 [==============================] - 2s 12ms/step - loss: 364959968.0000 - mae: 14113.4141 - val_loss: 416812800.0000 - val_mae: 14773.3223
Epoch 59/180
164/164 [==============================] - 2s 11ms/step - loss: 358949920.0000 - mae: 13972.0508 - val_loss: 426587520.0000 - val_mae: 15727.2295
Epoch 60/180
164/164 [==============================] - 2s 11ms/step - loss: 363468032.0000 - mae: 14170.8232 - val_loss: 431558016.0000 - val_mae: 15418.7510
Epoch 61/180
164/164 [==============================] - 2s 11ms/step - loss: 360604032.0000 - mae: 14069.6455 - val_loss: 423144000.0000 - val_mae: 15098.9561
Epoch 62/180
164/164 [==============================] - 2s 10ms/step - loss: 352054624.0000 - mae: 13842.4258 - val_loss: 440537152.0000 - val_mae: 15255.0684
Epoch 63/180
164/164 [==============================] - 2s 12ms/step - loss: 362912192.0000 - mae: 14126.8887 - val_loss: 401966624.0000 - val_mae: 14775.2041
Epoch 64/180
164/164 [==============================] - 2s 11ms/step - loss: 358905120.0000 - mae: 13947.6416 - val_loss: 410631648.0000 - val_mae: 14957.5889
Epoch 65/180
164/164 [==============================] - 2s 10ms/step - loss: 348742944.0000 - mae: 13776.9561 - val_loss: 401558304.0000 - val_mae: 14666.3555
Epoch 66/180
164/164 [==============================] - 2s 10ms/step - loss: 362756896.0000 - mae: 14128.0049 - val_loss: 400565632.0000 - val_mae: 14657.7568
Epoch 67/180
164/164 [==============================] - 2s 11ms/step - loss: 351007296.0000 - mae: 13811.8291 - val_loss: 402716576.0000 - val_mae: 14886.1113
Epoch 68/180
164/164 [==============================] - 2s 12ms/step - loss: 363372768.0000 - mae: 14232.6875 - val_loss: 430906368.0000 - val_mae: 15278.5986
Epoch 69/180
164/164 [==============================] - 2s 11ms/step - loss: 359481984.0000 - mae: 14137.0059 - val_loss: 413969088.0000 - val_mae: 14782.0547
Epoch 70/180
164/164 [==============================] - 2s 11ms/step - loss: 358425568.0000 - mae: 14023.0654 - val_loss: 413980704.0000 - val_mae: 15199.0752
Epoch 71/180
164/164 [==============================] - 2s 11ms/step - loss: 352975040.0000 - mae: 13848.9053 - val_loss: 485634912.0000 - val_mae: 16565.6895
Epoch 72/180
164/164 [==============================] - 2s 15ms/step - loss: 353928064.0000 - mae: 13963.4248 - val_loss: 419693792.0000 - val_mae: 14814.6719
Epoch 73/180
164/164 [==============================] - 2s 13ms/step - loss: 350550912.0000 - mae: 13777.0352 - val_loss: 479384832.0000 - val_mae: 16508.0664
Epoch 74/180
164/164 [==============================] - 2s 12ms/step - loss: 361722016.0000 - mae: 14051.3652 - val_loss: 405575328.0000 - val_mae: 14708.4873
Epoch 75/180
164/164 [==============================] - 2s 15ms/step - loss: 351852192.0000 - mae: 13826.7451 - val_loss: 402719936.0000 - val_mae: 14660.1797
Epoch 76/180
164/164 [==============================] - 2s 11ms/step - loss: 349838336.0000 - mae: 13766.2598 - val_loss: 401083840.0000 - val_mae: 14862.3906
Epoch 77/180
164/164 [==============================] - 2s 12ms/step - loss: 357215840.0000 - mae: 14034.2441 - val_loss: 423748320.0000 - val_mae: 15206.9209
Epoch 78/180
164/164 [==============================] - 2s 11ms/step - loss: 355055648.0000 - mae: 13960.0410 - val_loss: 478395136.0000 - val_mae: 16301.7051
Epoch 79/180
164/164 [==============================] - 2s 12ms/step - loss: 362323072.0000 - mae: 14083.7236 - val_loss: 408249248.0000 - val_mae: 14712.3379
Epoch 80/180
164/164 [==============================] - 2s 12ms/step - loss: 367961440.0000 - mae: 14189.6641 - val_loss: 419219520.0000 - val_mae: 14918.0215
Epoch 81/180
164/164 [==============================] - 3s 17ms/step - loss: 350520960.0000 - mae: 13834.7129 - val_loss: 415416736.0000 - val_mae: 15584.7461
Epoch 82/180
164/164 [==============================] - 2s 12ms/step - loss: 357076800.0000 - mae: 14029.8613 - val_loss: 406057056.0000 - val_mae: 14901.5420
Epoch 83/180
164/164 [==============================] - 2s 14ms/step - loss: 362422912.0000 - mae: 14093.0059 - val_loss: 452710240.0000 - val_mae: 16291.2061
Epoch 84/180
164/164 [==============================] - 3s 17ms/step - loss: 361587360.0000 - mae: 14064.5938 - val_loss: 424169696.0000 - val_mae: 15081.7852
Epoch 85/180
164/164 [==============================] - 2s 14ms/step - loss: 355400416.0000 - mae: 13832.8916 - val_loss: 401034720.0000 - val_mae: 14853.5771
Epoch 86/180
164/164 [==============================] - 2s 14ms/step - loss: 350456128.0000 - mae: 13798.7910 - val_loss: 429148448.0000 - val_mae: 14964.9590
Epoch 87/180
164/164 [==============================] - 2s 14ms/step - loss: 355448096.0000 - mae: 13880.5342 - val_loss: 436121216.0000 - val_mae: 15986.1494
Epoch 88/180
164/164 [==============================] - 3s 16ms/step - loss: 354762752.0000 - mae: 13859.5332 - val_loss: 417639232.0000 - val_mae: 14598.0088
Epoch 89/180
164/164 [==============================] - 2s 13ms/step - loss: 359929984.0000 - mae: 14036.0352 - val_loss: 397417568.0000 - val_mae: 14794.9072
Epoch 90/180
164/164 [==============================] - 2s 15ms/step - loss: 357929696.0000 - mae: 14074.8232 - val_loss: 417232032.0000 - val_mae: 14936.7373
Epoch 91/180
164/164 [==============================] - 2s 14ms/step - loss: 353312480.0000 - mae: 13872.5049 - val_loss: 406557056.0000 - val_mae: 14643.8652
Epoch 92/180
164/164 [==============================] - 2s 13ms/step - loss: 350372128.0000 - mae: 13756.0791 - val_loss: 417149632.0000 - val_mae: 14969.3447
Epoch 93/180
164/164 [==============================] - 2s 11ms/step - loss: 359688288.0000 - mae: 14078.5225 - val_loss: 452428032.0000 - val_mae: 15760.6963
Epoch 94/180
164/164 [==============================] - 2s 11ms/step - loss: 360689920.0000 - mae: 14070.7998 - val_loss: 399815264.0000 - val_mae: 14936.5068
Epoch 95/180
164/164 [==============================] - 2s 13ms/step - loss: 364676032.0000 - mae: 14130.9531 - val_loss: 429079712.0000 - val_mae: 15467.0615
Epoch 96/180
164/164 [==============================] - 2s 13ms/step - loss: 352292576.0000 - mae: 13810.2227 - val_loss: 404690944.0000 - val_mae: 14908.4551
Epoch 97/180
164/164 [==============================] - 2s 13ms/step - loss: 355322720.0000 - mae: 13908.8701 - val_loss: 417759776.0000 - val_mae: 14841.4746
Epoch 98/180
164/164 [==============================] - 2s 14ms/step - loss: 358508832.0000 - mae: 13893.7959 - val_loss: 418723296.0000 - val_mae: 14846.9326
Epoch 99/180
164/164 [==============================] - 3s 16ms/step - loss: 351253056.0000 - mae: 13845.2041 - val_loss: 399268960.0000 - val_mae: 14571.2031
Epoch 100/180
164/164 [==============================] - 2s 13ms/step - loss: 360542560.0000 - mae: 14024.3311 - val_loss: 416079072.0000 - val_mae: 15069.0264
Epoch 101/180
164/164 [==============================] - 2s 13ms/step - loss: 353208256.0000 - mae: 13970.7783 - val_loss: 432262752.0000 - val_mae: 15176.5664
Epoch 102/180
164/164 [==============================] - 2s 15ms/step - loss: 352309664.0000 - mae: 13790.7910 - val_loss: 408163840.0000 - val_mae: 15127.4170
Epoch 103/180
164/164 [==============================] - 2s 13ms/step - loss: 357015008.0000 - mae: 14013.4658 - val_loss: 432325920.0000 - val_mae: 15156.9424
Epoch 104/180
164/164 [==============================] - 2s 11ms/step - loss: 355907200.0000 - mae: 13968.5264 - val_loss: 405725408.0000 - val_mae: 14558.9678
Epoch 105/180
164/164 [==============================] - 3s 17ms/step - loss: 345579584.0000 - mae: 13674.6309 - val_loss: 393878944.0000 - val_mae: 14316.3721
Epoch 106/180
164/164 [==============================] - 2s 12ms/step - loss: 354153728.0000 - mae: 13903.3193 - val_loss: 406276288.0000 - val_mae: 14765.8291
Epoch 107/180
164/164 [==============================] - 2s 12ms/step - loss: 350369824.0000 - mae: 13825.4385 - val_loss: 406369056.0000 - val_mae: 14974.9082
Epoch 108/180
164/164 [==============================] - 2s 12ms/step - loss: 348376352.0000 - mae: 13800.3115 - val_loss: 451602432.0000 - val_mae: 15689.7363
Epoch 109/180
164/164 [==============================] - 3s 18ms/step - loss: 353487392.0000 - mae: 13850.2109 - val_loss: 396899968.0000 - val_mae: 14296.9297
Epoch 110/180
164/164 [==============================] - 3s 17ms/step - loss: 357797152.0000 - mae: 13882.7969 - val_loss: 463410400.0000 - val_mae: 16067.5938
Epoch 111/180
164/164 [==============================] - 3s 16ms/step - loss: 353607200.0000 - mae: 13859.8584 - val_loss: 405271968.0000 - val_mae: 14880.7148
Epoch 112/180
164/164 [==============================] - 3s 17ms/step - loss: 344124736.0000 - mae: 13674.2432 - val_loss: 398914848.0000 - val_mae: 14478.4092
Epoch 113/180
164/164 [==============================] - 2s 14ms/step - loss: 351142784.0000 - mae: 13724.9180 - val_loss: 408618496.0000 - val_mae: 14659.7744
Epoch 114/180
164/164 [==============================] - 2s 12ms/step - loss: 350340768.0000 - mae: 13731.5664 - val_loss: 396558432.0000 - val_mae: 14518.8779
Epoch 115/180
164/164 [==============================] - 2s 15ms/step - loss: 345457824.0000 - mae: 13800.6963 - val_loss: 414590016.0000 - val_mae: 14612.8994
Epoch 116/180
164/164 [==============================] - 2s 13ms/step - loss: 360353056.0000 - mae: 14031.1543 - val_loss: 413804256.0000 - val_mae: 14725.8613
Epoch 117/180
164/164 [==============================] - 2s 13ms/step - loss: 352624768.0000 - mae: 13771.6777 - val_loss: 396122560.0000 - val_mae: 14478.2002
Epoch 118/180
164/164 [==============================] - 2s 13ms/step - loss: 357793248.0000 - mae: 13994.3867 - val_loss: 446201952.0000 - val_mae: 15376.5850
Epoch 119/180
164/164 [==============================] - 2s 13ms/step - loss: 354686048.0000 - mae: 13936.1836 - val_loss: 424903744.0000 - val_mae: 15496.9209
Epoch 120/180
164/164 [==============================] - 2s 15ms/step - loss: 346785568.0000 - mae: 13742.6699 - val_loss: 425624000.0000 - val_mae: 14921.5791
Epoch 121/180
164/164 [==============================] - 2s 12ms/step - loss: 350540896.0000 - mae: 13826.9189 - val_loss: 405928384.0000 - val_mae: 14948.3477
Epoch 122/180
164/164 [==============================] - 2s 12ms/step - loss: 357967872.0000 - mae: 13874.0977 - val_loss: 400020384.0000 - val_mae: 14493.8271
Epoch 123/180
164/164 [==============================] - 2s 14ms/step - loss: 354469504.0000 - mae: 13841.4141 - val_loss: 473097920.0000 - val_mae: 16607.5410
Epoch 124/180
164/164 [==============================] - 3s 16ms/step - loss: 352187040.0000 - mae: 13819.4775 - val_loss: 414532992.0000 - val_mae: 14870.9180
Epoch 125/180
164/164 [==============================] - 2s 14ms/step - loss: 355189248.0000 - mae: 13937.8652 - val_loss: 444879872.0000 - val_mae: 15612.6064
Epoch 126/180

In [64]:
# Evaluate
loss, mae = model.evaluate(X_test, y_test, verbose=0)
print(f"Test MAE: {mae:.2f}")

Test MAE: 15105.25

2. Relative to Salary Range (350 – 250,000)
Salary range ≈ 249,650
Normalized MAE = 23,929 ÷ 249,650 ≈ 9.6% of the full range


3. Relative to Mean Salary (~95,000)
Normalized MAE = 23,929 ÷ 95,000 ≈ 25% of average salary
This is high → predictions are off by about a quarter of the typical salary.

4. Interpretation
<10% of mean salary → excellent
10–15% → acceptable
>20% → needs improvement

5. Final Target 
For this dataset:
Aim for MAE = 10k–15k
That would be ~10–15% of mean salary, which is a much better performance.

In [65]:
model.save("Salary Deep Model.H5")

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: Salary Deep Model.H5\assets

INFO:tensorflow:Assets written to: Salary Deep Model.H5\assets